id: P003114
initial_creation_type: ocr
source_metadata:
  id: bdr:W30337
  title: དག་སྣང་ཡེ་ཤེས་དྲྭ་བ་ལས་གནས་ལུགས་རང་བྱུང་གི་རྒྱུད་རྡོ་རྗེའི་སྙིང་པོ
  author: ''
  volumes:
    8bf17b6aa7554bf1ad7d16d9162ff9de:
      image_group_id: I6078
      title: ''
      volume_number: 1
      total_pages: 710
