id: P003114
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:41:12.014013
source_metadata:
  id: bdr:W30337
  title: དག་སྣང་ཡེ་ཤེས་དྲྭ་བ་ལས་གནས་ལུགས་རང་བྱུང་གི་རྒྱུད་རྡོ་རྗེའི་སྙིང་པོ
  author: ''
  volumes:
    8bf17b6aa7554bf1ad7d16d9162ff9de:
      image_group_id: I6078
      title: ''
      volume_number: 1
      total_pages: 710
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
