id: ID0284DE0
legacy_id: P003114
ocr_import_info:
  bdrc_scan_id: W30337
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T18:13:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:32:19.706121+00:00'
last_modified: 2022-09-03 19:32:36.219717
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30337
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW30337
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དག་སྣང་ཡེ་ཤེས་དྲྭ་བ་ལས་གནས་ལུགས་རང་བྱུང་གི་རྒྱུད་རྡོ་རྗེའི་སྙིང་པོ།
  author: བདུད་འཇོམས་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.5957840495139194
  ocr_word_median_confidence_index: 0.6200000047683716
quality: null
bases:
  I6078:
    source_metadata:
      id: http://purl.bdrc.io/resource/I6078
      total_pages: 710
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I6078.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.5957840495139194
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
