id: ID0284DE0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T18:18:31+00:00'
last_modified: '2022-06-07T17:41:16.838057+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30337
  title: དག་སྣང་ཡེ་ཤེས་དྲྭ་བ་ལས་གནས་ལུགས་རང་བྱུང་གི་རྒྱུད་རྡོ་རྗེའི་སྙིང་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0A0B:
      image_group_id: I6078
      title: ''
      total_pages: 710
      order: 1
      base_file: 0A0B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
